package com.iyouth.common.login.vo;
// Generated 6 Jan, 2011 11:55:20 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * LoginLogoutDetails generated by hbm2java
 */
public class LoginLogoutDetails implements java.io.Serializable {

    private Integer id;
    private String sessionId;
    private Integer userId;
    private Date loginTime;
    private Date logOutTime;

    public LoginLogoutDetails() {
    }

    public LoginLogoutDetails(String sessionId) {
        this.sessionId = sessionId;
    }

    public LoginLogoutDetails(String sessionId, Integer userId, Date loginTime, Date logOutTime) {
        this.sessionId = sessionId;
        this.userId = userId;
        this.loginTime = loginTime;
        this.logOutTime = logOutTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSessionId() {
        return this.sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Date getLogOutTime() {
        return logOutTime;
    }

    public void setLogOutTime(Date logOutTime) {
        this.logOutTime = logOutTime;
    }

    public Date getLoginTime() {
        return loginTime;
    }

    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}
